name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: 1.8
        distribution: temurin # Specify the distribution here
